[package]
name = "ddi3cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.6.2"
portable-pty = "0.8.1"
ipnetwork = "*"
